### ISSUE TITLE
fix failing test case psithon2 and dftd3-psithon2

### ISSUE THREAD

**Issue by psi4** [psi4/psi4public#124]
This is probably an environment issue wrt PSIDATADIR, PSIPATH and details that didn't thoroughly translated to cmake.

**Comment by kannon92** [comment]
This does not work for me.

**Comment by kannon92** [comment]
This is fixed in the private repository.

**Comment by ryanmrichard** [comment]
Fix is merged in commit ba521818764a33a72cc8ac3d3991a3b522bd22c2

**Comment by CDSherrill** [comment]
dftd3-psithon2 still doesn't work for me on psi4public .  Has it been merged?
